config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :students
  resources :students
  
  devise_for :teachers
  resources :teachers
  
  devise_for :subjects
  resources :subjects
  
  devise_for :block_classes
  resources :block_classes
  
  devise_for :lectures
  resources :lectures
  
  devise_for :assignments
  resources :assignments
  
  devise_for :comments
  resources :comments
  
  devise_for :exam_schedules
  resources :exam_schedules
  
  devise_for :exams
  resources :exams
  
  devise_for :courses
  resources :courses
  
  devise_for :users
  resources :users do
    collection do
      put :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'subjects/:id/lectures' => 'subjects#lectures', as: :subject_lectures
  get 'subjects/:id/assignments' => 'subjects#assignments', as: :subject_assignments
  get 'subjects/:id/exam_schedules' => 'subjects#exam_schedules', as: :subject_exam_schedules
  get 'exam_schedules/:id/exam_index' => 'exam_schedules#exam_index', as: :exam_schedule_exam_index
  get 'block_classes/:id/destroy_subject' => 'block_classes#destroy_subject', as: :destroy_block_class_subject
  get 'subjects/:id/destroy_block_class' => 'subjects#destroy_block_class', as: :destroy_subject_block_class
  get '/dashboard' => 'users#dashboard', as: :dashboard

  match "/404", :to => "errors#not_found", via: :all
  match "/500", :to => "errors#internal_server_error", via: :all

  root 'users#dashboard'
end

app/models/student.rb
class Student < User
  belongs_to :block_class
  belongs_to :course
  has_many :exams
  
  validates :block_class_id, :course, presence: true
  
  def average_score
    sum = 0
    self.exams.each do |exam|
      sum += exam.transmuted_score
    end
    if self.exams.count > 0
      sum / self.exams.count
    else
      0
    end
  end
  
  def subject_average(subject)
    sum = 0.0
    count = 0
    subject.exam_schedules.each do |exam_schedule|
      exam_schedule.exams.where(student: self).each do |exam|
        count += 1
        if exam.grade
          sum += exam.grade
        else
          return nil
        end
      end
    end
    sum / count
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.paginate(page: params[:page], per_page: 10).includes(:block_class).includes(:exams)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @exams = Exam.where(student: @student)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.fetch(:student, {}).permit(:username, :last_name, :first_name, :password, :avatar, :email, :password_confirmation, :course_id, :block_class_id)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<%= render partial:'/layouts/validations', locals: {model: @student} %>

<br />
<div class="well well-sm col-md-6 col-md-offset-3" style="padding:25px">
	<%= form_for @student do |f| %>
		<div class="form-horizontal">
			<fieldset <%= @student == current_user ? "" : 'disabled'%>>
				<center><%= image_tag (@student.avatar ? @student.avatar(:icon) : "images/missing.jpg"), id: "output", class: "img-rounded avatar_preview", style: "height:100px" %></center><br />
		    <%= f.file_field :avatar, id:"input" %><br />
				<script>
				  function handleFileSelect(evt) {
				    var files = evt.target.files; // FileList object
				      f=files[0]
				      // Only process image files.
				      if (f.type.match('image.*')) {
				        var reader = new FileReader();
				        reader.onload = (function(theFile) {
				          return function(e) {
				            // alert(e.target.result);
				            document.getElementById("output").src=e.target.result;
				          };
				        })(f);

				      // Read in the image file as a data URL.
				      reader.readAsDataURL(f);
				      }
				    }
				  document.getElementById('input').addEventListener('change', handleFileSelect, false);
				</script>
			</fieldset>
	
			<fieldset disabled>
				<div class="form-group">
			    <label for="username" class=" col-sm-2 control-label">Username</label>
					<div class=" col-sm-10">
				    <%= f.text_field :username, class: "form-control input-sm", id:"username", required: true %>
					</div>
				</div>
			</fieldset>
		
			<fieldset <%= @student == current_user ? "" : 'disabled'%>>
				<div class="form-group">
			    <label for="first_name" class=" col-sm-2 control-label">Name</label>
					<div class=" col-sm-10">
				    <%= f.text_field :first_name, class: "form-control input-sm", id:"first_name", required: true %>
					</div>
				</div>
	
				<div class="form-group">
			    <label for="last_name" class=" col-sm-2 control-label">Surname</label>
					<div class=" col-sm-10">
				    <%= f.text_field :last_name, class: "form-control input-sm", id:"last_name", required: true %>
					</div>
				</div>
			</fieldset>
	
			<div class="form-group">
		    <label for="email" class=" col-sm-2 control-label">Email</label>
				<div class=" col-sm-10">
			    <%= f.text_field :email, class: "form-control input-sm", sr:"email", required: true %>
				</div>
			</div>
			
			<fieldset <%= current_user.admin? ? "" : 'disabled'%>>
				<div class="form-group">
			    <label for="course" class=" col-sm-2 control-label">Course</label>
					<div class=" col-sm-10">
						<%= f.select :course, options_from_collection_for_select(Course.all, 'id', 'name'), {}, class:"form-control select2", required: true %>
			    </div>
				</div>
				
				<div class="form-group">
			    <label for="block_class_id" class=" col-sm-2 control-label">Block</label>
					<div class=" col-sm-10">
				    <%= f.select :block_class_id, options_from_collection_for_select(BlockClass.all, 'id', 'name'), {}, class: "form-control select2", id:"block_class_id", required: true %>
					</div>
				</div>
			</fieldset>
			
			<fieldset <%= @student == current_user ? "" : 'disabled'%>>
				<span class="help-block"><small>Leave blank to retain current password</small></span>
				<%= f.label :new_password, class:"sr-only" %>
		    <%= f.password_field :password, class: "form-control input-sm", placeholder: "New Password" %><br />
	
				<%= f.label :new_password_confirmation, class:"sr-only" %>
		    <%= f.password_field :password_confirmation, class: "form-control input-sm", placeholder: "Confirm New Password" %><br />
			</fieldset>

			<%= f.submit "Submit", class: "btn btn-primary btn-block btn-sm" %>
		</div>
	<% end %>
	<center><%= link_to "Back to Profile", @student %></center>
</div>

app/views/students/index.html.erb
<br />
<div class="well well-sm col-md-10 col-md-offset-1">
	<h1>Students</h1>
	<div class="table-responsive">
		<table class="table table-striped">
			<th>Name</th>
			<th>ID No.</th>
			<th>Email</th>
			<th>Block</th>
			<th>Yr.</th>
			<th>Course</th>
			<th width="100px"> </th>
			<% @students.each do |student| %>
			  <tr>
					<td><%= link_to "#{student.last_name}, #{student.first_name}", student %></td>
					<td><%= link_to student.username, student %>
					<td><%= mail_to student.email %></td>
					<td><%= student.block_class ? (link_to student.block_class.name, student.block_class) : "" %>
					<td><%= student.year_level %></td>
					<td><%= link_to student.course.name, student.course %></td>
			    <td max-width="100px">
					<% if can? :manage, student %>
							<%= link_to "Edit", edit_student_path(student), class:"btn btn-primary btn-xs" %>
							<% unless student.admin? %>
								<%= link_to "Delete", student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
							<% end %>
					<% end %>
					</td>
			  </tr>
			<% end %>
			<tr>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td>
					<% if can? :create, 'Students' %>
						<%= link_to 'Create', new_student_path, class: "btn btn-primary btn-xs" %><br />
					<% end %>
				</td>
			</tr>
		</table>
	</div>

	<center><%= page_entries_info @students %><br/>
	<%= will_paginate @students, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/students/new.html.erb
<%= render partial:'/layouts/validations', locals: {model: @student} %>

<br />
<div class="well well-sm col-md-4 col-md-offset-4">
	<%= form_for @student do |f| %>
	
		<% generated_username = Time.now.strftime("%y") + (Student.count+1).to_s.rjust(4, '0') %>
		<div class="form-group">
			<%= f.label :username, class:"sr-only" %>
			<%= f.text_field :username, value: generated_username, readonly: true, class:"form-control" %><br />

			<%= f.label :course_id, class:"sr-only" %>
			<%= f.select :course_id, options_from_collection_for_select(Course.all, 'id', 'name'), {include_blank: " - Select Course - "}, class:"select2 form-control", required: true %><br />

			<%= f.label :block_class_id, class:"sr-only" %>
			<%= f.select :block_class_id, options_from_collection_for_select(BlockClass.all, 'id', 'name'), {include_blank: " - Select Block - "}, class:"select2 form-control", required: true %>

			<%= f.hidden_field :first_name, value: generated_username %>
			<%= f.hidden_field :last_name, value: generated_username %>
			<%= f.hidden_field :password, value: generated_username %>
			<%= f.hidden_field :password_confirmation, value: generated_username %>
			<%= f.hidden_field :email, value: "#{generated_username}@#{generated_username}.com" %>
	    <br />
			<%= f.submit "Submit", class:"btn btn-primary btn-block" %>
			
			<center>
				<%= link_to "Back to Students", students_path%>
			</center>
	  </div>
	<% end %>
</div>

app/views/students/show.html.erb
<table style="margin:1%; height:160px">
	<td>
		<%= image_tag @student.avatar.url(:icon), class: "img-rounded" %>
	</td>
	<td style="padding: 10px">
		<h3>
			<strong><%= @student.first_name %> <%= @student.last_name %></strong>
			<small>#<%= @student.username %></small>
		</h3>
		<%= @student.year_level %> <%= @student.course.name %><br />
		<% if @student.block_class%>
			<%= link_to "Block #{@student.block_class.name}", @student.block_class %><br />
		<% end %>
		<%= mail_to @student.email %><br />
		<% if @student.id == current_user.id || current_user.admin? %>
			<%= link_to 'Edit', edit_student_path, class: "btn btn-primary btn-xs" %>
		<% end %>
		<%= link_to 'Back to students', students_path, class: "btn btn-primary btn-xs" %>
	</td>
</table>

<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
<% if @student == current_user || @student.block_class.teacher == current_user || current_user.admin? %>
		<ul class="nav nav-tabs" id="myTab">
			<% @student.block_class.subjects.each do |subject| %>
			  <li><a data-target="#<%=subject.name%>" data-toggle="tab"><%=subject.name%></a></li>
			<% end %>
		</ul>

		<div class="tab-content" style="height: 285px; overflow-y:scroll">
			<% @student.block_class.subjects.each do |subject| %>
		  <div class="tab-pane" id="<%=subject.name%>">
				<strong>Subject: <%= link_to subject.name, subject %></strong><br /><br />
				<strong>Exam Schedules</strong>
				<table class="table table-striped">
					<th width="100px">Date Posted</th>
					<th>Title</th>
					<th width="100px">Date</th>
					<th width="100px"><%= current_user == @student ? "Grade" : "" %></th>
					<% subject.exam_schedules.each do |exam_schedule| %>
						<tr>
							<td><%= exam_schedule.created_at.localtime.strftime("%e %b, %Y") %></td>
							<td><%= link_to truncate(exam_schedule.title, length:18), exam_schedule %></td>
							<td><%= exam_schedule.date ? exam_schedule.date.localtime.strftime("%e %b, %Y") : "" %></td>
							<td>
								<% if current_user == @student || current_user == @student.block_class.teacher %>
									<% unless exam_schedule.exams.find_by(student: @student).try(:grade) %>
										<% if current_user == exam_schedule.subject.teacher %>
											<%= link_to "(GRADE)", edit_exam_path(exam_schedule.exams.find_by(student: @student)) %>
										<% elsif current_user == @student %>
											<%= link_to "n.a.", exam_path(exam_schedule.exams.find_by(student: @student)) %>
										<% else %>
											n.a.
										<% end %>
									<% else %>
										<% if current_user == exam_schedule.subject.teacher || current_user == @student %>
											<%= link_to exam_schedule.exams.find_by(student: @student).grade, exam_path(exam_schedule.exams.find_by(student: @student)) %>
										<% else %>
											<%= exam_schedule.exams.find_by(student: @student).grade %>
										<% end %>
									<% end %>
									/
									<%= exam_schedule.max_score %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</table>
				
				<strong>Assignments</strong>
				<table class="table table-striped">
					<th width="100px">Date Posted</th>
					<th>Title</th>
					<% subject.assignments.each do |assignment| %>
						<tr>
							<td><%= assignment.created_at.localtime.strftime("%e %b, %Y") %></td>
							<td><%= link_to truncate(assignment.title, length:50 ), assignment %></td>
						</tr>
					<% end %>
				</table>
				
				<strong>Lectures</strong>
				<table class="table table-striped">
					<th width="100px">Date Posted</th>
					<th>Title</th>
					<% subject.lectures.each do |lecture| %>
						<tr>
							<td><%= lecture.created_at.localtime.strftime("%e %b, %Y") %></td>
							<td><%= link_to truncate(lecture.title, length:50 ), lecture %></td>
						</tr>
					<% end %>
				</table>
			</div>
			<% end %>
		</div>
	</div>
<% else %>
	<table class="table table-striped">
		<strong>Subjects</strong>
		<th>Name</th>
		<th>Teacher</th>
		<% @student.block_class.subjects.each do |subject| %>
			<tr>
				<td><%= link_to subject.name, subject %></td>
				<td><%= link_to "#{subject.teacher.last_name}, #{subject.teacher.first_name}", subject.teacher %></td>
			</tr>
		<% end %>
	</table>
<% end %>
</div>

<% if @student.block_class.present? %>
	<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
		<strong><%= link_to "Block #{@student.block_class.name}", @student.block_class %></strong><br />
			<div style="height: 310px; overflow-y:scroll">
				<table class="table">
					<th>Name</th>
					<th>ID No.</th>
					<th> </th>
					<% @student.block_class.students.each do |student| %>
						<tr>
							<td><%= link_to "#{student.last_name}, #{student.first_name}", student_path(student) %></td>
							<td><%= student.username %></td>
							<% if current_user == @student.block_class.teacher %><td><%= student.average_score.round(2) %><% end %></td>
						</tr>
					<% end %>
				</table>
			</div>
	</div>
<% end %>