config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :students
  resources :students
  
  devise_for :teachers
  resources :teachers
  
  devise_for :subjects
  resources :subjects
  
  devise_for :block_classes
  resources :block_classes
  
  devise_for :lectures
  resources :lectures
  
  devise_for :assignments
  resources :assignments
  
  devise_for :comments
  resources :comments
  
  devise_for :exam_schedules
  resources :exam_schedules
  
  devise_for :exams
  resources :exams
  
  devise_for :courses
  resources :courses
  
  devise_for :users
  resources :users do
    collection do
      put :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'subjects/:id/lectures' => 'subjects#lectures', as: :subject_lectures
  get 'subjects/:id/assignments' => 'subjects#assignments', as: :subject_assignments
  get 'subjects/:id/exam_schedules' => 'subjects#exam_schedules', as: :subject_exam_schedules
  get 'exam_schedules/:id/exam_index' => 'exam_schedules#exam_index', as: :exam_schedule_exam_index
  get 'block_classes/:id/destroy_subject' => 'block_classes#destroy_subject', as: :destroy_block_class_subject
  get 'subjects/:id/destroy_block_class' => 'subjects#destroy_block_class', as: :destroy_subject_block_class
  get '/dashboard' => 'users#dashboard', as: :dashboard

  match "/404", :to => "errors#not_found", via: :all
  match "/500", :to => "errors#internal_server_error", via: :all

  root 'users#dashboard'
end

app/controllers/block_classes_controller.rb
class BlockClassesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_block_class, only: [:show, :edit, :update, :destroy, :destroy_subject]

  # GET /block_classes
  # GET /block_classes.json
  def index
    @block_classes = BlockClass.all.paginate(page: params[:page], per_page: 10).includes(:students, :teacher)
  end

  # GET /block_classes/1
  # GET /block_classes/1.json
  def show
  end

  # GET /block_classes/new
  def new
    @block_class = BlockClass.new
  end

  # GET /block_classes/1/edit
  def edit
    @teachers = Teacher.all
  end

  # POST /block_classes
  # POST /block_classes.json
  def create
    @block_class = BlockClass.new(block_class_params)

    respond_to do |format|
      if @block_class.save
        format.html { redirect_to @block_class, notice: 'Block class was successfully created.' }
        format.json { render :show, status: :created, location: @block_class }
      else
        format.html { render :new }
        format.json { render json: @block_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /block_classes/1
  # PATCH/PUT /block_classes/1.json
  def update
    respond_to do |format|
      if @block_class.update(block_class_params)
        format.html { redirect_to @block_class, notice: 'Block class was successfully updated.' }
        format.json { render :show, status: :ok, location: @block_class }
      else
        format.html { render :edit }
        format.json { render json: @block_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /block_classes/1
  # DELETE /block_classes/1.json
  def destroy
    @block_class.destroy
    respond_to do |format|
      format.html { redirect_to block_classes_url, notice: 'Block class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def destroy_subject
    @subject = Subject.find(params[:subject_id])
    redirect_to block_class_path
    @block_class.subjects.destroy(@subject)
    flash[:notice] = "#{@subject.name} succesfully cancelled."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block_class
      @block_class = BlockClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_class_params
      params.fetch(:block_class, {}).permit(:name, :teacher_id)
    end
end

app/helpers/block_classes_helper.rb
module BlockClassesHelper
end

app/views/block_classes/_form.html.erb
<%= render partial:'/layouts/validations', locals: {model: @block_class} %>

<%= form_for @block_class do |f| %>
	<br/>
	<div class="well well-sm col-md-4 col-md-offset-4">
		<div class="form-group">
			<%= f.text_field :name, class:"form-control", placeholder:"Block name", required: true %><br />
				
			<%= f.select :teacher_id, options_from_collection_for_select((Teacher.includes(:block_class).where(block_classes: { id: nil }) + Teacher.where(id: @block_class.teacher_id)), 'id', 'last_name', @block_class.teacher_id), {include_blank: "- Select Adviser -"} , class: 'form-control select2' %><br />
		  
			<%= f.submit "Submit", class:"btn btn-primary btn-block" %>
			
			<center>
				<% if @block_class.id? %>
					<%= link_to "Cancel", block_class_path(@block_class) %><br />
				<% end %>
				<%= link_to "Back to Blocks", block_classes_path %>
			</center>
		</div>
	</div>
<% end %>

app/views/block_classes/edit.html.erb
<%= render 'form', block_class: @block_class %>

app/views/block_classes/index.html.erb
<br />
<div class="well well-sm col-md-6 col-md-offset-3">
	<h1>Blocks</h1>
	<div class="table-responsive">
		<table class="table table-striped">
			<th>Name</th>
			<th>Adviser</th>
			<th>Students</th>
			<th max-width="100px"> </th>
			<% @block_classes.each do |block_class| %>
			  <tr>
					<td><%= link_to "Block #{block_class.name}", block_class %></td>
					<td><%= block_class.teacher ? (link_to "#{block_class.teacher.last_name}, #{block_class.teacher.first_name}", block_class.teacher) : "" %>
					<td><%= block_class.students.count %></td> 
				  <td>
				  <% if can? :manage, block_class %>
							<%= link_to "Edit", edit_block_class_path(block_class), class:"btn btn-primary btn-xs "%>
							<%= link_to "Delete", block_class, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					<% end %>
					</td>	
			  </tr>
			<% end %>
			<tr>
				<td> </td>
				<td> </td>
				<td> </td>
				<td>
					<% if can? :manage, 'BlockClass' %>
						<%= link_to 'Create', new_block_class_path, class: "btn btn-primary btn-xs" %><br />
					<% end %>
				</td>
			</tr>
		</table>
	</div>

	<center><%= page_entries_info @block_classes %><br/>
	<%= will_paginate @block_classes, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/block_classes/new.html.erb
<%= render 'form', block_class: @block_class %>

app/views/block_classes/show.html.erb
<table style="margin:1%; height:160px">
	<td>
		<h3><strong>Block <%= @block_class.name %></strong><br /></h3>
		Adviser: <%= link_to "#{@block_class.teacher.last_name}, #{@block_class.teacher.first_name}", @block_class.teacher %><br />
		<% if current_user.admin? %>
			<%= link_to 'Edit', edit_block_class_path, class: "btn btn-primary btn-xs" %>
		<% end %>
		<%= link_to 'Back to Blocks', block_classes_path, class: "btn btn-primary btn-xs" %>
	</td>
</table>

<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
	<strong>Students</strong><br />
	<div style="height: 310px; overflow-y:scroll">
		<table class="table table-striped">
			<th>Name</th>
			<th>ID No.</th>
			<th><%= current_user == @block_class.teacher ? "Average" : "" %></th>
			<% @block_class.students.each do |student| %>
				<tr>
					<td><%= link_to "#{student.last_name}, #{student.first_name}", student %></td>
					<td><%= student.username %></td>
					<td><% if current_user == @block_class.teacher %><%= student.average_score.round(2) %><% end %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
	<strong>Subjects</strong><br />
	<div style="height: 310px; overflow-y:scroll">
		<br />
		<table class="table table-striped">
			<% @block_class.subjects.each do |subject| %>
				<tr>
					<td>
						<%= link_to subject.name, subject_path(subject) %>
					</td>
					<td>
						<a href='<%= subject_lectures_path %>' class="btn btn-primary btn-xs">Lectures</a>
						<a href='<%= subject_assignments_path %>' class="btn btn-primary btn-xs">Assignments</a>
						<a href='<%= subject_exam_schedules_path %>' class="btn btn-primary btn-xs">Exam Schedules</a>
						<% if current_user.admin? %>
							<%= link_to "Cancel", destroy_block_class_subject_path(subject_id: subject.id), class:"btn btn-danger btn-xs", data: { confirm: 'Are you sure you want to cancel this class?' } %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</table>
	</div>
</div>