config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :students
  resources :students
  
  devise_for :teachers
  resources :teachers
  
  devise_for :subjects
  resources :subjects
  
  devise_for :block_classes
  resources :block_classes
  
  devise_for :lectures
  resources :lectures
  
  devise_for :assignments
  resources :assignments
  
  devise_for :comments
  resources :comments
  
  devise_for :exam_schedules
  resources :exam_schedules
  
  devise_for :exams
  resources :exams
  
  devise_for :courses
  resources :courses
  
  devise_for :users
  resources :users do
    collection do
      put :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'subjects/:id/lectures' => 'subjects#lectures', as: :subject_lectures
  get 'subjects/:id/assignments' => 'subjects#assignments', as: :subject_assignments
  get 'subjects/:id/exam_schedules' => 'subjects#exam_schedules', as: :subject_exam_schedules
  get 'exam_schedules/:id/exam_index' => 'exam_schedules#exam_index', as: :exam_schedule_exam_index
  get 'block_classes/:id/destroy_subject' => 'block_classes#destroy_subject', as: :destroy_block_class_subject
  get 'subjects/:id/destroy_block_class' => 'subjects#destroy_block_class', as: :destroy_subject_block_class
  get '/dashboard' => 'users#dashboard', as: :dashboard

  match "/404", :to => "errors#not_found", via: :all
  match "/500", :to => "errors#internal_server_error", via: :all

  root 'users#dashboard'
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :students
  has_many :block_classes, through: :students
  
  validates :name, presence: true, uniqueness: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :block_classes
  belongs_to :teacher
  has_many :lectures
  has_many :assignments
  has_many :exam_schedules
  
  validates :name, presence: true, uniqueness: true
  validates :teacher_id, :block_class_ids, presence: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all.paginate(page: params[:page], per_page: 10).includes(:teacher)
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end
  
  def lectures
    @subject = Subject.find(params[:id])
    @lectures = @subject.lectures
  end
  
  def assignments
    @subject = Subject.find(params[:id])
    @assignments = @subject.assignments
  end
  
  def exam_schedules
    @subject = Subject.find(params[:id])
    @exam_schedules = @subject.exam_schedules
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def destroy_block_class
    @block_class = BlockClass.find(params[:block_class_id])
    redirect_to subject_path
    @subject.block_classes.destroy(@block_class)
    flash[:notice] = "Block #{@block_class.name} succesfully removed."
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subject_params
    params.fetch(:subject, {}).permit(:name, :teacher_id, {block_class_ids: []})
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= render partial:'/layouts/validations', locals: {model: @subject} %>

<%= form_for @subject do |f| %>
	<br/ >
	<div class="well well-sm col-md-4 col-md-offset-4">
	  <div class="form-group form">
	    <%= f.text_field :name, class:"form-control", autofocus:true, placeholder:"Subject Name"%><br />
		
			<%= f.select :teacher_id, options_from_collection_for_select(Teacher.all, 'id', 'last_name', @subject.teacher_id), {include_blank: '- Select Professor -'} , class: 'form-control select2' %><br />
			
			<%= f.select :block_class_ids, options_from_collection_for_select(BlockClass.all, 'id', 'name', @subject.block_class_ids), {include_blank: '- Select Blocks -'}, class: 'form-control select2', multiple:true %><br />
			
			<%= f.submit "Submit", class:"btn btn-primary btn-block" %>
			
			<center>
				<% if @subject.id %>
					<%= link_to "Cancel", subject_path(@subject) %><br />
				<% end %>
				<%= link_to "Back to Subjects", subjects_path %>
			</center>
	  </div>
	</div>
<% end %>

app/views/subjects/assignments.html.erb
<br />
<div class="well well-sm col-md-6 col-md-offset-3 table-responsive">
	<strong>Assignments for <%= link_to @subject.name %></strong><br />
	<table class="table table-striped">
		<th style="width: 100px">Date Posted</th>
		<th>Title</th>
		<th max-width="100px"> </th>
		<% @assignments.order(created_at: :desc).each do |assignment| %>
			<tr>
				<td align="right">
					<div>
						<%= assignment.created_at.localtime.strftime("%e %b %Y") %><br />
					</div>
				</td>
				<td><%= link_to "#{truncate(assignment.title, length:40)}", assignment %></td>
				<td>
					<% if can? :edit, assignment %>
						<%= link_to "Edit", edit_assignment_path(assignment, params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs" %>
						<%= link_to "Delete", assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					<% end %>
				</td>
		<% end %>
	</table>
	<% if current_user == @subject.teacher %>
		<center><%= link_to "New Assignment", new_assignment_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
	<% end %>
		
	<center>
		<%= link_to "Back to Subject", @subject %>
	</center>
</div>

app/views/subjects/edit.html.erb
<%= render 'form', subject: @subject %>

app/views/subjects/exam_schedules.html.erb
<br />
<div class="well well-sm col-md-6 col-md-offset-3 table-responsive">
	<strong>Exam Schedules for <%= link_to @subject.name %></strong><br />
	<table class="table table-striped">
		<th style="width: 100px">Date Posted</th>
		<th>Title</th>
		<th width="100px">Exam Date</th>
		<th max-width="50px">Grade</th>
		<th max-width="100px"> </th>
		<% @exam_schedules.order(created_at: :desc).each do |exam_schedule| %>
			<tr>
				<td align="right">
					<div>
						<%= exam_schedule.created_at.localtime.strftime("%e %b %Y") %><br />
					</div>
				</td>
				<td><%= link_to truncate(exam_schedule.title, length:20), exam_schedule %></td>
				<td>
					<%= exam_schedule.date ? exam_schedule.date.localtime.strftime("%e %b %Y") : "" %><br />
				</td>
				<td>
					<%= exam_schedule.exams.find_by(student: current_user) ? "#{exam_schedule.exams.find_by(student: current_user).grade} / " : "" %>
					<%= exam_schedule.max_score %>
				</td>
				<td>
					<% if can? :edit, exam_schedule %>
						<%= link_to "Edit", edit_exam_schedule_path(exam_schedule, params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs" %>
						<%= link_to "Delete", exam_schedule, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					<% end %>
				</td>
		<% end %>
	</table>
	<% if current_user == @subject.teacher %>
		<center><%= link_to "New Exam Schedule", new_exam_schedule_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
	<% end %>
		
	<center>
		<%= link_to "Back to Subject", @subject %>
	</center>
</div>

app/views/subjects/index.html.erb
<br />
<div class="well well-sm col-sm-6 col-sm-offset-3">
	<h1>Subject</h1>
	<div class="table-responsive">
		<table class="table table-striped">
			<th>Name</th>
			<th>Teacher</th>
			<th max-width="100px"> </th>
			<% @subjects.each do |subject| %>
			  <tr>
					<td><%= link_to subject.name, subject %></td>
					<td><%= subject.teacher ? (link_to "#{subject.teacher.last_name}, #{subject.teacher.first_name}", subject.teacher) : "" %>
			    <td>
					<% if can? :manage, subject %>
							<%= link_to "Edit", edit_subject_path(subject), class:"btn btn-primary btn-xs" %>
							<%= link_to "Delete", subject, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					<% end %>
					</td>
			  </tr>
			<% end %>
			<tr>
				<td> </td>
				<td> </td>
				<td>
					<% if can? :manage, 'Teachers' %>
						<%= link_to 'Create', new_subject_path, class: "btn btn-primary btn-xs" %><br />
					<% end %>
				</td>
			</tr>
		</table>
	</div>

	<center><%= page_entries_info @subjects %><br/>
	<%= will_paginate @subjects, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/subjects/lectures.html.erb
<br />
<div class="well well-sm col-md-6 col-md-offset-3 table-responsive">
	<strong>Lectures for <%= link_to @subject.name %></strong><br />
	<table class="table table-striped">
		<th width="100px">Date Posted</th>
		<th>Title</th>
		<th width="100px"> </th>
		<% @lectures.order(created_at: :desc).each do |lecture| %>
			<tr>
				<td align="right">
					<div>
						<%= lecture.created_at.localtime.strftime("%e %b %Y") %><br />
					</div>
				</td>
				<td><%= link_to "#{truncate(lecture.title, length:40)}", lecture %></td>
					<td>
						<% if can? :edit, lecture %>
							<%= link_to "Edit", edit_lecture_path(lecture, params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs" %>
							<%= link_to "Delete", lecture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
					<% end %>
					</td>
		<% end %>
	</table>
	<% if current_user == @subject.teacher %>
		<center><%= link_to "New Lecture", new_lecture_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
	<% end %>
		
	<center>
		<%= link_to "Back to Subject", @subject %>
	</center>
</div>

app/views/subjects/new.html.erb
<%= render 'form', subject: @subject %>

app/views/subjects/show.html.erb
<table style="margin:1%; height:160px">
	<td>
		<h3><strong>Subject: <%= @subject.name %></strong><br /></h3>
		Teacher: <%= link_to "#{@subject.teacher.last_name}, #{@subject.teacher.first_name}", @subject.teacher %><br />
		<% if current_user.admin? %>
			<%= link_to 'Edit', edit_subject_path, class: "btn btn-primary btn-xs" %>
		<% end %>
		<%= link_to 'Back to Subjects', subjects_path, class: "btn btn-primary btn-xs" %>
	</td>
</table>

<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
	<ul class="nav nav-tabs" id="myTab">
	  <li class="active"><a data-target="#exam_schedules" data-toggle="tab">Exam Schedules</a></li>
	  <li><a data-target="#assignments" data-toggle="tab">Assignments</a></li>
	  <li><a data-target="#lectures" data-toggle="tab">Lectures</a></li>
	</ul>
	
	<div class="tab-content" style="max-height: 310px; overflow-y:scroll">
		<div class="tab-pane active" id="exam_schedules">
			<table class="table table-striped">
					<th width="100px">Date Posted</th>
					<th>Title</th>
					<th width="100px">Date</th>
					<th width="100px">Grade</th>
				<% @subject.exam_schedules.order(created_at: :desc).each do |exam_schedule| %>
					<tr>
						<td><%= exam_schedule.created_at.localtime.strftime("%e %b %Y") %></td>
						<td><%= link_to truncate(exam_schedule.title, length:25), exam_schedule %></td>
						<td><%= exam_schedule.date.localtime.strftime("%e %b %Y")%></td>
						<td>
							<%= exam_schedule.exams.find_by(student: current_user) ? "#{exam_schedule.exams.find_by(student: current_user).grade} / " : "" %>
							<%= exam_schedule.max_score %>
						</td>
				<% end %>
			</table>
			<% if current_user == @subject.teacher %>
				<center><%= link_to "New Exam Schedule", new_exam_schedule_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
			<% end %>
		</div>
	
		<div class="tab-pane" id="assignments">
			<table class="table table-striped">
				<th width="100px">Date</th>
				<th>Title</th>
				<% @subject.assignments.order(created_at: :desc).each do |assignment| %>
					<tr>
						<td><%= assignment.created_at.localtime.strftime("%e %b %Y") %></td>
						<td><%= link_to "#{truncate(assignment.title, length:60, separator: ' ')}", assignment %></td>
				<% end %>
			</table>
			<% if current_user == @subject.teacher %>
				<center><%= link_to "New Assignment", new_assignment_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
			<% end %>
		</div>
	
		<div class="tab-pane" id="lectures">
			<table class="table table-striped">
				<th width="100px">Date</th>
				<th>Title</th>
				<% @subject.lectures.order(created_at: :desc).each do |lecture| %>
					<tr>
						<td><%= lecture.created_at.localtime.strftime("%e %b %Y") %></td>
						<td><%= link_to "#{truncate(lecture.title, length:60, separator: ' ')}", lecture %></td>
				<% end %>
			</table>
			<% if current_user == @subject.teacher %>
				<center><%= link_to "New Lecture", new_lecture_path(params: {subject_id: @subject.id}), class:"btn btn-primary btn-xs"%></center>
			<% end %>
		</div>
	</div>
</div>

<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
	<strong>Blocks</strong><br />
	<div style="height: 310px; overflow-y:scroll">
		<table class="table table-striped">
			<th>Name</th>
			<th>Adviser</th>
			<% if current_user.admin? %>
			<th width="50px"> </th>
			<% end %>
			<% @subject.block_classes.each do |block_class| %>
				<tr>
					<td><%= link_to "Block #{block_class.name}", block_class %></td>
					<td><%= link_to "#{block_class.teacher.last_name}, #{block_class.teacher.first_name}", block_class.teacher %></td>
					<% if current_user.admin? %>
						<td><%= link_to "Cancel", destroy_subject_block_class_path(block_class_id: block_class.id), class:"btn btn-danger btn-xs", data: { confirm: 'Are you sure you want to remove this block?' } %></td>
					<% end %>
				</tr>
			<% end %>
		</table>
	</div>
</div>