config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :students
  resources :students
  
  devise_for :teachers
  resources :teachers
  
  devise_for :subjects
  resources :subjects
  
  devise_for :block_classes
  resources :block_classes
  
  devise_for :lectures
  resources :lectures
  
  devise_for :assignments
  resources :assignments
  
  devise_for :comments
  resources :comments
  
  devise_for :exam_schedules
  resources :exam_schedules
  
  devise_for :exams
  resources :exams
  
  devise_for :courses
  resources :courses
  
  devise_for :users
  resources :users do
    collection do
      put :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'subjects/:id/lectures' => 'subjects#lectures', as: :subject_lectures
  get 'subjects/:id/assignments' => 'subjects#assignments', as: :subject_assignments
  get 'subjects/:id/exam_schedules' => 'subjects#exam_schedules', as: :subject_exam_schedules
  get 'exam_schedules/:id/exam_index' => 'exam_schedules#exam_index', as: :exam_schedule_exam_index
  get 'block_classes/:id/destroy_subject' => 'block_classes#destroy_subject', as: :destroy_block_class_subject
  get 'subjects/:id/destroy_block_class' => 'subjects#destroy_block_class', as: :destroy_subject_block_class
  get '/dashboard' => 'users#dashboard', as: :dashboard

  match "/404", :to => "errors#not_found", via: :all
  match "/500", :to => "errors#internal_server_error", via: :all

  root 'users#dashboard'
end

app/models/teacher.rb
class Teacher < User
  has_one :block_class
  has_many :subjects
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all.paginate(page: params[:page], per_page: 10).includes(block_class: {students: :exams})
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.  
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def teacher_params
    params.fetch(:teacher, {}).permit(:username, :last_name, :first_name, :password, :avatar, :email, :password_confirmation, :is_admin)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
  <div class="form-horizontal">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, id:"input" %><br />
		
		<center><%= image_tag (@teacher.avatar ? @teacher.avatar(:thumb) : "images/missing.jpg"), id: "output", class: "img-rounded avatar_preview"%></center><br /><br />
		
		<script>
		  function handleFileSelect(evt) {
		    var files = evt.target.files; // FileList object
		      f=files[0]
		      // Only process image files.
		      if (f.type.match('image.*')) {
		        var reader = new FileReader();
		        reader.onload = (function(theFile) {
		          return function(e) {
		            // alert(e.target.result);
		            document.getElementById("output").src=e.target.result;
		          };
		        })(f);

		      // Read in the image file as a data URL.
		      reader.readAsDataURL(f);
		      }
		    }
		  document.getElementById('input').addEventListener('change', handleFileSelect, false);
		</script>
		
		<%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control input-sm" %><br />
		
		<%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control input-sm" %><br />
		
		<%= f.label :email %>
    <%= f.text_field :email, class: "form-control input-sm" %><br />

		<%= f.submit "Submit", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<%= render partial:'/layouts/validations', locals: {model: @teacher} %>

<br />
<div class="well well-sm col-md-6 col-md-offset-3" style="padding:25px">
	<%= form_for @teacher do |f| %>
	  <div class="form-horizontal">
			<fieldset <%= @teacher == current_user ? "" : 'disabled'%>>
				<center><%= image_tag (@teacher.avatar ? @teacher.avatar(:icon) : "images/missing.jpg"), id: "output", class: "img-rounded avatar_preview", style: "height:100px" %></center><br />
		    <%= f.file_field :avatar, id:"input" %><br />
				<script>
				  function handleFileSelect(evt) {
				    var files = evt.target.files; // FileList object
				      f=files[0]
				      // Only process image files.
				      if (f.type.match('image.*')) {
				        var reader = new FileReader();
				        reader.onload = (function(theFile) {
				          return function(e) {
				            // alert(e.target.result);
				            document.getElementById("output").src=e.target.result;
				          };
				        })(f);

				      // Read in the image file as a data URL.
				      reader.readAsDataURL(f);
				      }
				    }
				  document.getElementById('input').addEventListener('change', handleFileSelect, false);
				</script>
			</fieldset>
		
			<fieldset disabled>
				<div class= "form-group">
			    <label for= "username" class=" col-sm-2 control-label">Username</label>
					<div class= "col-sm-10">
				    <%= f.text_field :username, class: "form-control input-sm", id:"username", required: true %>
					</div>
				</div>
			</fieldset>
			
			<fieldset <%= @teacher == current_user ? "" : 'disabled'%>>
				<div class= "form-group">
			    <label for= "first_name" class=" col-sm-2 control-label">Name</label>
					<div class= "col-sm-10">
				    <%= f.text_field :first_name, class: "form-control input-sm", id:"first_name", required: true %>
					</div>
				</div>
		
				<div class= "form-group">
			    <label for= "last_name" class=" col-sm-2 control-label">Surname</label>
					<div class= "col-sm-10">
				    <%= f.text_field :last_name, class: "form-control input-sm", id:"last_name", required: true %>
					</div>
				</div>
			</fieldset>
		
			<div class= "form-group">
		    <label for= "email" class=" col-sm-2 control-label">Email</label>
				<div class= "col-sm-10">
			    <%= f.text_field :email, class: "form-control input-sm", required: true %>
				</div>
			</div>
		
			<% if current_user.admin? && current_user != @teacher %>
				<div class= "form-group">
			    <label for= "is_admin" class=" col-sm-2 control-label">Admin?</label>
					<div class= "col-sm-10">
				    <%= f.check_box :is_admin, class: "checkbox", style:"margin-top: 12px", required: true %>
					</div>
				</div>
			<% end %>
			
			<span class="help-block"><small>Leave blank to retain current password</small></span>
			<%= f.label :new_password, class:"sr-only" %>
	    <%= f.password_field :password, class: "form-control input-sm", placeholder: "New Password" %><br />
		
			<%= f.label :new_password_confirmation, class:"sr-only" %>
	    <%= f.password_field :password_confirmation, class: "form-control input-sm", placeholder: "Confirm New Password" %><br />

			<%= f.submit "Submit", class: "btn btn-primary btn-block btn-sm" %>
	  </div>
	<% end %>
	<center><%= link_to "Back to Profile", @teacher %></center>
</div>

app/views/teachers/index.html.erb
<br />
<div class="well well-sm col-md-8 col-md-offset-2">
	<h1>Teachers</h1>
	<div class="table-responsive">
		<table class="table table-striped">
			<th>Name</th>
			<th>ID No.</th>
			<th>Email</th>
			<th>Class</th>
			<th width="100px"> </th>
			<% @teachers.each do |teacher| %>
			  <tr>
					<td><%= link_to "#{teacher.last_name}, #{teacher.first_name}", teacher %></td>
					<td><%= link_to teacher.username, teacher %>
					<td><%= mail_to teacher.email %></td>
					<td><%= teacher.block_class ? (link_to teacher.block_class.name, teacher.block_class) : "" %>
			    <td>
					<% if can? :edit, teacher %>
						<%= link_to "Edit", edit_teacher_path(teacher), class:"btn btn-primary btn-xs" %>
					<% end %>
					<% if can? :delete, teacher %>
						<% unless teacher.admin? %>
							<%= link_to "Delete", teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
						<% end %>
					<% end %>
					</td>
			  </tr>
			<% end %>
			<tr>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td>
					<% if can? :create, 'Teachers' %>
						<%= link_to 'Create', new_teacher_path, class: "btn btn-primary btn-xs" %><br />
					<% end %>
				</td>
			</tr>
		</table>
	</div>

	<center><%= page_entries_info @teachers %><br/>
	<%= will_paginate @teachers, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/teachers/new.html.erb
<%= render partial:'/layouts/validations', locals: {model: @teacher} %>

<br />
<div class="well well-sm col-md-4 col-md-offset-4">
	<%= form_for @teacher do |f| %>
	
		<% generated_username = Time.now.strftime("%y") + (Teacher.count+1).to_s.rjust(3, '0') %>
		<div class="form-group">
			<%= f.label :username, class:"sr-only" %>
			<%= f.text_field :username, value: generated_username, readonly: true, class:"form-control" %>

			<%= f.label :password, class:"sr-only" %>
			<%= f.hidden_field :password, value: generated_username %>

			<%= f.label :password_confirmation, class:"sr-only" %>
			<%= f.hidden_field :password_confirmation, value: generated_username %>

			<%= f.label :email, class:"sr-only" %>
			<%= f.hidden_field :email, value: "#{generated_username}@#{generated_username}.com" %>

	    <br />
			<%= f.submit "Submit", class:"btn btn-primary btn-block" %>
			<center>
				<%= link_to "Back to Teachers", teachers_path %>
			</center>
	  </div>
	<% end %>
</div>

app/views/teachers/show.html.erb
<table style="margin:1%; height:160px">
	<td>
		<%= image_tag @teacher.avatar.url(:icon), class: "img-rounded" %>
	</td>
	<td style="padding: 10px">
		<h3>
			<strong><%= @teacher.first_name %> <%= @teacher.last_name %></strong>
			<small>#<%= @teacher.username %></small>
		</h3>
		<% if @teacher.block_class%>
			<%= link_to "Block #{@teacher.block_class.name}", @teacher.block_class %><br />
		<% end %>
		<%= mail_to @teacher.email %><br />
		<% if @teacher.id == current_user.id || current_user.admin? %>
			<%= link_to 'Edit', edit_teacher_path, class: "btn btn-primary btn-xs" %>
		<% end %>
		<%= link_to 'Back to Teachers', teachers_path, class: "btn btn-primary btn-xs" %>
	</td>
</table>

<% if @teacher.subjects.present? %>
	<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
		<strong>Subjects</strong><br />
			<div style="height: 310px; overflow-y:scroll">
				<table class="table">
					<% @teacher.subjects.each do |subject| %>
						<tr>
							<td><%= link_to subject.name, subject_path(subject) %></td>
							<td>
								<a href='<%= subject_lectures_path(subject) %>' class="btn btn-primary btn-xs" style="disabled: true">
									Lectures
								</a>
								<a href='<%= subject_assignments_path(subject) %>' class="btn btn-primary btn-xs">
									Assignments
								</a>
								<a href='<%= subject_exam_schedules_path(subject) %>' class="btn btn-primary btn-xs">
									Exams Schedules
								</a>
							</td>
						</tr>
					<% end %>
				</table>
			</div>
	</div>
<% end %>

<% if @teacher.block_class.present? %>
	<div class="well well-sm col-md-5 table-responsive" style="height: 350px; margin:1%; min-width:48%">
		<strong><%= link_to "Block #{@teacher.block_class.name}", block_class_path(@teacher.block_class) %></strong><br />
			<div style="height: 310px; overflow-y:scroll">
				<table class="table table-striped">
					<th>Name</th>
					<th>ID No.</th>
				<th><%= current_user == @teacher ? "Average" : "" %></th>
					<% @teacher.block_class.students.each do |student|%>
					<tr>
						<td><%= link_to "#{student.last_name}, #{student.first_name}", student_path(student) %></td>
						<td><%= student.username %></td>
						<% if current_user == @teacher %><td><%= student.average_score.round(2) %><% end %></td>
					</tr>
					<% end %>
				</table>
			</div>
	</div>
<% end %>